defaults:
  - model: base
  - task: question_answering

gs_base_path: '/home/m.pioro/nlp/project/poleval-2021'  # update with created bucket, eg. gs://my-bucket/my-path/

suffix: ''
model_dir: ${gs_base_path}/${hydra:runtime.choices.task}/models_v2/${hydra:runtime.choices.model}${suffix}
